#include<stdio.h>
#include<iostream>
#include<string.h>

using namespace std;

int main()
{
    int i,j,n,m,mini,t,k,l;
    cin>>t;
    for(k=0;k<t;k++)
    {
        string x,y;
        cin>>x>>y;
        int ins,d,r,kg,savei,savej;
        cin>>ins>>r>>kg;
        d=ins;
        n=x.length();
        m=y.length();
        int arr[100][100];
        if(ins==0)
            cout<<"0\n";
        else
        {
            for(i=0;i<n+1;i++)
            {
                if(d*i>kg)
                    break;
                arr[i][0]=d*i;
            }
            for(j=0;j<m+1;j++)
            {
                if(ins*j>kg)
                    break;
                arr[0][j]=ins*j;
            }
            savei=i;
            savej=j;
            for(i=1;i<savei;i++)
            {
                for(j=1;j<savej;j++)
                {
                    mini=arr[i-1][j]+d;
                    if(arr[i][j-1]+ins<=mini)
                    {
                        mini=arr[i][j-1]+ins;
                    }
                    if(x[i]==y[j])
                    {
                        if(arr[i-1][j-1]<=mini)
                            mini=arr[i-1][j-1];
                    }
                    else
                    {
                        if(arr[i-1][j-1]+r<=mini)
                        {
                            mini=arr[i-1][j-1]+r;
                        }
                    }
                    arr[i][j]=mini;
                }
                mini=arr[i][j-1]+ins;
                if(x[i]==y[j])
                {
                    if(arr[i-1][j-1]<=mini)
                        mini=arr[i-1][j-1];
                }
                else
                {
                    if(arr[i-1][j-1]+r<=mini)
                    {
                        mini=arr[i-1][j-1]+r;
                    }
                }
                arr[i][j]=mini;
                savej++;
            }
            int brr[1000]={0};
            int crr[1000]={0};
            int cnt,cnt2;
            for(j=0;j<savej;j++)
            {
                brr[j]=arr[savei-1][j];
            }
            cnt=0;
            cnt2=0;
            l=1;
            while(i<n+1)
            {
                for(j=l;j<savej;j++)
                {
                    if(cnt==0)
                    {
                            if(j==l)
                            {
                                mini=brr[j]+d;
                                if(x[i]==y[j])
                                {
                                    if(brr[j-1]<=mini)
                                        mini=brr[j-1];
                                }
                                else
                                {
                                    if(brr[j-1]+r<=mini)
                                    {
                                        mini=brr[j-1]+r;
                                    }
                                }
                                crr[j]=mini;
                            }
                            else
                            {
                                mini=brr[j]+d;
                                if(crr[j-1]+ins<=mini)
                                {
                                    mini=crr[j-1]+ins;
                                }
                                if(x[i]==y[j])
                                {
                                    if(brr[j-1]<=mini)
                                        mini=brr[j-1];
                                }
                                else
                                {
                                    if(brr[j-1]+r<=mini)
                                    {
                                        mini=brr[j-1]+r;
                                    }
                                }
                                crr[j]=mini;
                            }
                    }
                    else
                    {
                            if(j==l)
                            {
                                mini=crr[j]+d;
                                if(x[i]==y[j])
                                {
                                    if(crr[j-1]<=mini)
                                        mini=crr[j-1];
                                }
                                else
                                {
                                    if(crr[j-1]+r<=mini)
                                    {
                                        mini=crr[j-1]+r;
                                    }
                                }
                                brr[j]=mini;
                            }
                            else
                            {
                                mini=crr[j]+d;
                                if(brr[j-1]+ins<=mini)
                                {
                                    mini=brr[j-1]+ins;
                                }
                                if(x[i]==y[j])
                                {
                                    if(crr[j-1]<=mini)
                                        mini=crr[j-1];
                                }
                                else
                                {
                                    if(crr[j-1]+r<=mini)
                                    {
                                        mini=crr[j-1]+r;
                                    }
                                }
                                brr[j]=mini;
                            }
                    }
                }
                if(cnt2==0)
                {
                        if(cnt==0)
                        {
                                mini=crr[j-1]+ins;
                                if(x[i]==y[j])
                                {
                                    if(brr[j-1]<=mini)
                                        mini=brr[j-1];
                                }
                                else
                                {
                                    if(brr[j-1]+r<=mini)
                                    {
                                        mini=brr[j-1]+r;
                                    }
                                }
                                crr[j]=mini;
                        }
                        else
                        {
                                mini=brr[j-1]+ins;
                                if(x[i]==y[j])
                                {
                                    if(crr[j-1]<=mini)
                                        mini=crr[j-1];
                                }
                                else
                                {
                                    if(crr[j-1]+r<=mini)
                                    {
                                        mini=crr[j-1]+r;
                                    }
                                }
                                brr[j]=mini;
                        }
                        savej++;
                }
                l++;
                i++;
                cnt=1-cnt;
                if(cnt2==0 && savej>m)
                    cnt2=1;
            }
            if(savej<m)
                cout<<"-1\n";
            else
            {
                cnt=1-cnt;
                if(cnt==0)
                {
                    if(crr[m]<=kg)
                    cout<<crr[m]<<"\n";
                    else
                    cout<<"-1\n";
                }
                else
                {
                    if(brr[m]<=kg)
                    cout<<brr[m]<<"\n";
                    else
                    cout<<"-1\n";
                }
            }
        }
    }
    return 0;
}
